[tox]
envlist = test,lint,type,coverage

[testenv]
deps = {[dev]deps}

[dev]
deps =
    autoflake~=2.3
    black~=26.5
    build~=1.5
    flake8~=7.3
    mypy~=2.2
    pre-commit~=4.6
    pytest~=9.1
    pytest-cov~=7.1
    tox~=4.56
    twine~=6.2
    types-PyYAML~=6.0

[testenv:test]
commands = pytest tests/ -v --cov=pydes --cov-report=term-missing

[testenv:lint]
commands =
    flake8 src/pydes tests/
    black --check src/pydes tests/

[testenv:type]
commands = mypy src/pydes

[testenv:format]
commands =
    autoflake --in-place --remove-all-unused-imports --recursive src/pydes tests/
    black src/pydes tests/

[testenv:coverage]
commands = pytest tests/ -v --cov=pydes --cov-report=html --cov-report=term-missing --cov-fail-under=90

[flake8]
max-line-length = 88
extend-ignore = E203, E501
