name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install pip
        run: python pip install --upgrade pip

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.1
        env:
          CIBW_BUILD_VERBOSITY: 1

#      - uses: actions/upload-artifact@v2
#        with:
#          path: ./wheelhouse/*.whl
