name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels for Python ${{ matrix.python_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
        python_version: [3.6, 3.7, 3.8, 3.9]
        exclude:
          - os: windows-2019

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip
        run: pip3 install --upgrade pip

      - name: Install build script
        run: pip3 install --upgrade build

      - name: Build wheels
        run: python3 -m build
