name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]
        python_version: ["3.x"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip
        run: pip install --upgrade pip

      - name: Install build script
        run: pip install --upgrade build

      - name: Build wheels
        run: python -m build
